const menu = [
    {
        id: 1,
        title: "buttermilk pancakes",
        category: "Petit-déj",
        price: 15,
        img: "./images/item-1.jpeg",
        //desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
        desc: "",
        // ingredients: [" amande", "beurre de cacaouéte", "fraise"],
    },
    {
        id: 2,
        title: "Pizza Neptune",
        category: "Dejeuner",
        price: "14",
        img: "./images/pizza.jpg",
        desc: `Ingredients : , , , ,  `,
        // ingredients: [" tomate", "pignon", "olive", "thon", "fromage"],
    },
    {
        id: 3,
        title: "capucin",
        category: "Boissons",
        price: 2,
        img: "./images/capucin.jpg",
        desc: ``,
        // ingredients: [" amande", "beurre de cacaouéte", "fraise"],
    },
    {
        id: 4,
        title: "croissant",
        category: "Petit-déj",
        price: 1.2,
        img: "./images/coissant.jpg",
        desc: ``,
        // ingredients: [],
    },
    {
        id: 5,
        title: "sandwitch_kafteji",
        category: "Dejeuner",
        price: 6,
        img: "./images/sandwitch_kefteji.png",
        desc: "",
        // ingredients: ["pain speciale", "tomate", "pignon", "kafteji", "fritte"],
    },
    {
        id: 6,
        title: "Express",
        category: "Boissons",
        price: 2,
        img: "./images/espresso.jpeg",
        desc: ``,
        // ingredients: [],
    },
    {
        id: 7,
        title: "Pain_au_chocolat",
        category: "Petit-déj",
        price: 1,
        img: "./images/Pain_chocolat.jpg",
        desc: ` `,
        // ingredients: [],
    },
    {
        id: 8,
        title: "Sandwitch_Thon",
        category: "Dejeuner",
        price: 4,
        img: "./images/sandwitch_thon.jpg",
        desc: ``,
        // ingredients: ["tomate", " pignon", "thon", "fritte"],
    },
    {
        id: 9,
        title: "creme",
        category: "Boissons",
        price: 3,
        img: "./images/creme.jpg",
        desc: ``,
        // ingredients: [],
    },
    {
        id: 10,
        title: "Sandwitch_escalopes",
        category: "Dejeuner",
        price: 8,
        img: "./images/sandwitch_escaloppe.jpeg",
        desc: ``,
        // ingredients: ["tomate", "pignon", "kafteji", "fritte"],
    },
    {
        id: 11,
        title: "Citronade",
        category: "Boissons",
        price: 8,
        img: "./images/citronnade.jpg",
        desc: ``,
        // ingredients: [],
    },
];
export default menu;
